services:
  embedding-service:
    build: 
      context: .
      dockerfile: Dockerfile.cpu
    ports:
      - "12111:12111"
    shm_size: "4g"
    command: ["--model", "BAAI/bge-m3", "--port", "12111", "--host", "0.0.0.0"]
